/planner_node:
  ros__parameters:
    online: false
    timer_period: 5.0

    overtake_trigger_ittc: 1.3 #0.65
    overtake_trigger_steering_ang: 1.0

    brake_dist_threshold: 0.2

    reward_time_reset: 10

/sim_map_node:
  ros__parameters:
    online: false # set the parameter to true while testing on the vehicle

    sim_map_path: "src/f1tenth_gym_ros/maps/final_race_clean" #should be changed to particle filter on the vehicle
    sim_map_img_ext: ".pgm"
    sim_num_agents: 1

    fov: 60.0
    obs_threshold: 0.5

/get_obs_node:
  ros__parameters:
    online: false

    fov: 60.0
    obs_threshold: 1.5


/executer_node:
  ros__parameters:
    online: false # set the parameter to true while testing on the vehicle

    # pure pursuit params
    pp_look_ahead_distance: 1.5
    pp_kp: 0.5
    pp_high_speed: 6.0
    pp_medium_speed: 4.5
    pp_low_speed: 3.0
    waypoints_path: "src/final_pkg/path/using.csv"

    # rrt params
    rrt_look_ahead_dist: 2.2
    rrt_track_dist: 1.0
    rrt_bubble_offset: 1
    rrt_iter: 2000
    rrt_check_pts_num: 10
    rrt_max_expansion_dist: 1.0
    rrt_obs_clear_rate: 20
    rrt_kp: 0.3
    rrt_high_speed: 6.0
    rrt_medium_speed: 4.5
    rrt_low_speed: 3.0
    rrt_search_radius: 1.5
    rrt_hit_dist: 0.2
    rrt_star_enable: true
    rrt_ema_enable: true
    rrt_ema_alpha: 0.6

    block_kp: 1.0
    block_ki: 0.0
    block_kd: 0.0

    brake_speed: 2.0

/opponent_node:
  ros__parameters:
    online: false # set the parameter to true while testing on the vehicle

    # pure pursuit params
    pp_look_ahead_distance: 1.5
    pp_kp: 0.5
    pp_high_speed: 4.5
    pp_medium_speed: 3.5
    pp_low_speed: 2.5
    waypoints_path: "src/final_pkg/path/using.csv"

    # rrt params
    rrt_look_ahead_dist: 2.5
    rrt_track_dist: 0.5
    rrt_bubble_offset: 2
    rrt_iter: 8000
    rrt_check_pts_num: 10
    rrt_max_expansion_dist: 1.0
    rrt_obs_clear_rate: 5
    rrt_kp: 0.15
    rrt_high_speed: 6.0
    rrt_medium_speed: 4.5
    rrt_low_speed: 2.5
    rrt_search_radius: 1.5
    rrt_hit_dist: 0.1
    rrt_star_enable: true
    rrt_ema_enable: true
    rrt_ema_alpha: 0.6

    block_kp: 1.0
    block_ki: 0.0
    block_kd: 0.0
