/planner_node:
  ros__parameters:
    timer_period: 5.0

/executer_node:
  ros__parameters:
    online: false
    pp_look_ahead_distance: 1.4
    pp_kp: 0.5
    waypoints_path: "src/final_pkg/path/using.csv"
